USE WAREHOUSE PCOLINMAIRE_WH_XS;
USE SCHEMA INFRACTIONS;

CREATE OR REPLACE FILE FORMAT "PCOLINMAIRE_DB"."INFRACTIONS".CSV_INFRACTIONS TYPE = 'CSV'
 COMPRESSION = 'AUTO'
 FIELD_DELIMITER = ';'
 RECORD_DELIMITER = '\n'
 SKIP_HEADER = 1
 FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
 TRIM_SPACE = FALSE
 ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
 ESCAPE = 'NONE'
 ESCAPE_UNENCLOSED_FIELD = '\134'
 DATE_FORMAT = 'AUTO'
 TIMESTAMP_FORMAT = 'AUTO'
 NULL_IF = ('\\N');


CREATE OR REPLACE STAGE "PCOLINMAIRE_DB"."INFRACTIONS".STAGE_S3_INFRACTIONS 
 URL = 's3://pcolinmaire-poc-infractions/infractions'
 CREDENTIALS = (AWS_KEY_ID = 'AKIAWRA2CTWR4FNJENXN' 
					AWS_SECRET_KEY = '+AkKmkw/hckulofZyCKXsAMRnHLVCR0d0OWY1PlO')
 FILE_FORMAT = CSV_INFRACTIONS;
--CREATE OR REPLACE STAGE STAGE_SF
--  FILE_FORMAT = CSV_SF;

TRUNCATE TABLE DSA_DATA_GLOB;
  
--PUT 'file://D:/WorkingFolder/trunk/LabPerso/SanFrancisco/data/data.csv' @STAGE_SF;

LIST @STAGE_S3_INFRACTIONS;

COPY INTO DSA_DATA_GLOB
	FROM @STAGE_S3_INFRACTIONS
	PATTERN='infractions/DATA_GLOB_\\d{2}.csv'
	ON_ERROR = 'skip_file'
    FORCE = TRUE;
	
	
SELECT *
FROM DSA_DATA_GLOB;
--COPY INTO SF_RAW_DATA FROM @STAGE_SF/data.csv

DROP FILE FORMAT CSV_INFRACTIONS;
DROP STAGE STAGE_S3_INFRACTIONS;
--DROP TABLE DSA_DATA_GLOB;

